# This confirms that the repo is properly formatted according
# to the information located in README-HEADER.md

name: Format

on:
  pull_request:
    # Run tests when PRs opened or updated
    types: [opened, synchronize]
    branches:
      - main
concurrency: format-${{ github.base_ref }}
jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup rtx
        uses: jdx/rtx-action@v1

      - name: "Format"
        run: ./scripts/format.sh

      - name: "Confirm"
        run: |
          if [[ ! -z $(git status --porcelain) ]]; then
            echo "Repo is not canonically formatted. Run ./scripts/format.sh"
            exit 1
          fi
