name: Lint

on:
  pull_request:
    # Run linter when PRs opened or updated
    types: [opened, synchronize]
    branches:
      - main
concurrency: lint-${{ github.base_ref }}
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Cache asdf
        id: asdf-cache
        uses: actions/cache@v2
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Setup asdf
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v1

      - name: "Lint"
        run: ./scripts/lint.sh
