# This confirms that the repo is properly validated according
# to the information located in README-HEADER.md

name: Validate

on:
  pull_request:
    # Run tests when PRs opened or updated
    types: [opened, synchronize]
    branches:
      - main
concurrency: validate-${{ github.base_ref }}
jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup rtx
        uses: jdx/rtx-action@v1

      - name: "Validate Module"
        run: ./scripts/validate.sh
